In [ ]:
#Brouillons

# On cherche à prédire la lessure et la capacité à performer 
# Ce qu'on pourrait avoir besoin : age , capacité de travail , repas , charge d'entrainement..

# D'après des sites ,les blessures arrivent à cause de : pathologies liées à un surmenage sportif // 
# geste mal exécuté // Le surentraînement // méconnaissance de la discipline pratiquée ( gestes ou postures inadéquats, ou un équipement mal adapté) //
# mouvement brusque // Des contraintes ou mouvements répétitifs // Des “points faibles” dans notre anatomie // 
# Une hygiène sportive inadéquate ( échauffement ou récupération insuffisante, manque de préparation physique )

In [2]:
import pandas as pd

In [25]:
overview=pd.read_excel("../data/Test_technique/participant-overview.xlsx",header=1)
overview

,Participant ID,Age,Height,Gender,A or B person,Max heart rate,Date,Minutes,Seconds,Stride walk,Stride run
0,p01,48,195,male,A,182,2019-11-26 00:00:00,29,33,80.90,102.9
1,p02,60,180,male,A,169,2019-12-15 00:00:00,23,51,74.70,92.4
2,p03,25,184,male,A,157,2019-12-30 00:00:00,33,22,NaN,NaN
3,p04,26,163,female,A,195,2019-11-19 00:00:00,22,13,67.30,110.2
4,p05,35,176,male,A,184,2019-12-23 00:00:00,32,40,73.00,94.3
5,p06,42,179,male,B,181,2019-12-01 00:00:00,23,19,73.04,97.6
6,p07,26,177,male,B,NaN,2019-11-19 00:00:00,19,40,73.50,119.5
7,p08,27,186,male,B,200,2019-11-28 00:00:00,18,47,77.20,103.6
8,p09,26,180,male,B,183,2020-01-07 00:00:00,35,6,74.70,109.9
9,p10,38,179,female,B,197,2019-12-08 00:00:00,28,10,73.09,102.3
10,p11,25,171,female,A,203,november,26,15,70.60,98.9
11,p12,27,178,male,A,,2019-12-17 00:00:00,30,22,NaN,NaN
12,p13,31,183,male,A,186,2019-11-11 00:00:00,30,16,75.90,105.6
13,p14,45,181,male,A,190,november,26,15,75.10,11.3
14,p15,54,180,male,A,NaN,injured,injured,injured,74.70,88.1
15,p16,23,182,male,B,199,2020-11-16 00:00:00,47,28,75.50,128.8

In [10]:
wellness=pd.read_csv("../data/Test_technique/p01/pmsys/wellness.csv")
wellness.head()

,effective_time_frame,fatigue,mood,readiness,sleep_duration_h,sleep_quality,soreness,soreness_area,stress
0,2019-11-01T08:31:40.751Z,2,3,5,6,3,2,[12921003],3
1,2019-11-02T10:00:01.229Z,2,3,6,6,3,2,[12921003],3
2,2019-11-03T14:28:03.263Z,3,3,8,6,3,3,[],3
3,2019-11-04T07:05:28.429Z,3,3,8,6,3,3,[],3
4,2019-11-05T06:13:35.998Z,3,3,8,5,3,3,[],3

In [12]:
srpe=pd.read_csv("../data/Test_technique/p01/pmsys/srpe.csv")
srpe.head()

,end_date_time,activity_names,perceived_exertion,duration_min
0,2019-11-05T22:51:54.710Z,"['individual', 'running']",7,30
1,2019-11-11T21:15:15.092Z,"['individual', 'running']",6,30
2,2019-11-14T21:00:53.000Z,"['team', 'soccer']",7,60
3,2019-11-18T21:34:44.995Z,"['individual', 'endurance']",6,50
4,2019-11-21T21:06:25.146Z,"['team', 'soccer']",6,70

In [22]:
injury=pd.read_csv("../data/Test_technique/p01/pmsys/injury.csv")
injury.head(12)

        effective_time_frame                 injuries
0   2019-11-07T06:39:48.428Z                       {}
1   2019-11-11T13:47:05.617Z                       {}
2   2019-11-18T08:28:53.208Z                       {}
3   2019-11-25T08:10:11.478Z                       {}
4   2019-12-02T08:10:19.841Z                       {}
5   2019-12-09T08:17:02.463Z                       {}
6   2019-12-16T08:16:54.735Z                       {}
7   2019-12-25T11:04:39.750Z                       {}
8   2019-12-30T08:17:02.019Z                       {}
9   2020-01-04T16:20:58.607Z                       {}
10  2020-01-06T05:39:54.344Z                       {}
11  2020-01-07T22:33:38.989Z  {'right_hand': 'minor'}

In [21]:
steps=pd.read_json("../data/Test_technique/p01/fitbit/steps.json")
steps.head()

             dateTime  value
0 2019-11-01 00:00:00      0
1 2019-11-01 00:01:00      0
2 2019-11-01 00:02:00      0
3 2019-11-01 00:03:00      0
4 2019-11-01 00:04:00      0

In [28]:
sleep_score=pd.read_csv("../data/Test_technique/p01/fitbit/sleep_score.csv")
sleep_score.head()

,timestamp,sleep_log_entry_id,overall_score,composition_score,revitalization_score,duration_score,deep_sleep_in_minutes,resting_heart_rate,restlessness
0,2019-11-01T06:29:30Z,24472394143,76,18,20,38,27,53,0.053635
1,2019-11-02T07:19:30Z,24486013387,79,20,22,37,36,53,0.078978
2,2019-11-03T07:34:30Z,24497341340,71,16,17,38,38,52,0.093491
3,2019-11-04T06:35:00Z,24507914069,68,15,15,38,37,53,0.064851
4,2019-11-05T06:25:00Z,24521896102,73,15,22,36,26,54,0.093185

In [48]:
reporting=pd.read_csv("../data/Test_technique/p01/googledocs/reporting.csv")
reporting.head()

,date,timestamp,meals,weight,glasses_of_fluid,alcohol_consumed
0,06/11/2019,06/12/2019 21:58:30,"Breakfast, Dinner",100.0,7,No
1,09/11/2019,09/12/2019 21:17:02,"Breakfast, Evening",100.0,6,No
2,10/11/2019,10/12/2019 21:52:58,"Breakfast, Lunch, Dinner",100.0,9,No
3,11/11/2019,11/11/2019 22:36:30,"Breakfast, Dinner",100.0,5,No
4,12/11/2019,13/11/2019 00:15:47,"Breakfast, Lunch, Dinner",100.0,7,No

In [34]:
calories=pd.read_json("../data/Test_technique/p01/fitbit/calories.json")
calories.head()

             dateTime  value
0 2019-11-01 00:00:00   1.39
1 2019-11-01 00:01:00   1.39
2 2019-11-01 00:02:00   1.39
3 2019-11-01 00:03:00   1.39
4 2019-11-01 00:04:00   1.39

In [44]:
resting_heart_rate=pd.read_json("../data/Test_technique/p01/fitbit/resting_heart_rate.json")
resting_heart_rate["rhr"]=resting_heart_rate["value"].apply(lambda d: d["value"])
resting_heart_rate[["dateTime","rhr"]].head()

    dateTime        rhr
0 2019-11-01  53.741074
1 2019-11-02  52.881497
2 2019-11-03  53.222024
3 2019-11-04  54.311141
4 2019-11-05  52.259110

In [40]:
distance=pd.read_json("../data/Test_technique/p01/fitbit/distance.json")
distance.head()

             dateTime  value
0 2019-11-01 00:00:00      0
1 2019-11-01 00:01:00      0
2 2019-11-01 00:02:00      0
3 2019-11-01 00:03:00      0
4 2019-11-01 00:04:00      0

In [56]:
exercise=pd.read_json("../data/Test_technique/p01/fitbit/exercise.json")
exercise.head(20)

,logId,activityName,activityTypeId,activityLevel,averageHeartRate,calories,duration,activeDuration,steps,logType,...,elevationGain,hasGps,shouldFetchDetails,distance,distanceUnit,source,tcxLink,speed,pace,vo2Max
0,26451905128,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",94,192,1331000,1331000,1878,auto_detected,...,24.384,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,26455950499,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",94,302,2202000,2202000,2786,auto_detected,...,27.432,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,26467488515,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",98,354,2458000,2458000,3035,auto_detected,...,21.336,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,26520401069,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",97,145,1024000,1024000,1284,auto_detected,...,21.336,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,26538035127,Walk,90013,"[{'minutes': 3, 'name': 'sedentary'}, {'minute...",93,121,973000,973000,1065,auto_detected,...,3.048,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,26517400839,Run,90009,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",144,396,1465000,1460000,3901,tracker,...,38.405,True,True,3.846164,Kilometer,"{'type': 'tracker', 'name': 'Versa 2', 'id': '...",https://www.fitbit.com/activities/exercise/265...,9.341901,385.360523,{'vo2Max': 47.37765}
6,26601718322,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",97,252,1844000,1844000,2094,auto_detected,...,24.384,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,26613177504,Walk,90013,"[{'minutes': 1, 'name': 'sedentary'}, {'minute...",97,454,3123000,3123000,4185,auto_detected,...,64.008,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,26777647969,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",106,470,2867000,2867000,4698,auto_detected,...,30.480,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,26664863611,Run,90009,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",146,339,1264000,1260000,3384,tracker,...,12.497,True,True,3.445945,Kilometer,"{'type': 'tracker', 'name': 'Versa 2', 'id': '...",https://www.fitbit.com/activities/exercise/266...,9.713571,370.615486,{'vo2Max': 47.012370000000004}
10,26675122494,Walk,90013,"[{'minutes': 1, 'name': 'sedentary'}, {'minute...",88,104,922000,922000,867,auto_detected,...,3.048,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,26725195544,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",101,292,1997000,1997000,2303,auto_detected,...,21.336,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,26736567295,Sport,15000,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",119,633,3175000,3175000,3915,auto_detected,...,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,26738177333,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",97,195,1485000,1485000,1524,auto_detected,...,21.336,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,26744627929,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",114,221,1126000,1126000,2152,auto_detected,...,0.000,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,26745672435,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",113,248,1229000,1229000,2265,auto_detected,...,39.624,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,26749431814,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",98,351,2560000,2560000,2761,auto_detected,...,42.672,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,26760309680,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",106,173,973000,973000,1373,auto_detected,...,30.480,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,26765476301,Sport,15000,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",96,141,1126000,1126000,780,auto_detected,...,NaN,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,26769331684,Walk,90013,"[{'minutes': 0, 'name': 'sedentary'}, {'minute...",110,166,921000,921000,1332,auto_detected,...,24.384,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
heart_rate=pd.read_json("../data/Test_technique/p01/fitbit/heart_rate.json")
heart_rate["bpm"]=heart_rate["value"].apply(lambda d: d["bpm"])
heart_rate["confidence"]=heart_rate["value"].apply(lambda d: d["confidence"])
heart_rate[["dateTime","bpm","confidence"]].head(10)

             dateTime  bpm  confidence
0 2019-11-01 00:00:05   54           3
1 2019-11-01 00:00:10   52           3
2 2019-11-01 00:00:20   51           3
3 2019-11-01 00:00:25   52           3
4 2019-11-01 00:00:30   51           3
5 2019-11-01 00:00:35   52           3
6 2019-11-01 00:00:45   53           3
7 2019-11-01 00:00:50   56           3
8 2019-11-01 00:00:55   54           3
9 2019-11-01 00:01:00   53           3

In [53]:
sleep=pd.read_json("../data/Test_technique/p01/fitbit/sleep.json")
sleep.head()

,logId,dateOfSleep,startTime,endTime,duration,minutesToFallAsleep,minutesAsleep,minutesAwake,minutesAfterWakeup,timeInBed,efficiency,type,infoCode,levels,mainSleep
0,24486013387,2019-11-02,2019-11-02 00:09:30,2019-11-02T07:19:30.000,25800000,0,378,52,0,430,97,stages,0,"{'summary': {'deep': {'count': 2, 'minutes': 3...",True
1,24497341340,2019-11-03,2019-11-03 00:32:00,2019-11-03T07:34:30.000,25320000,0,378,44,0,422,96,stages,0,"{'summary': {'deep': {'count': 2, 'minutes': 3...",True
2,24507914069,2019-11-04,2019-11-03 23:55:30,2019-11-04T06:35:00.000,23940000,0,361,38,0,399,96,stages,0,"{'summary': {'deep': {'count': 2, 'minutes': 3...",True
3,24521896102,2019-11-05,2019-11-05 00:22:30,2019-11-05T06:25:00.000,21720000,0,326,36,1,362,99,stages,0,"{'summary': {'deep': {'count': 1, 'minutes': 2...",True
4,24534036899,2019-11-06,2019-11-06 00:25:30,2019-11-06T06:29:30.000,21840000,0,341,23,1,364,99,stages,0,"{'summary': {'deep': {'count': 2, 'minutes': 6...",True

In [62]:
time_in_hrzone=pd.read_json("../data/Test_technique/p01/fitbit/time_in_heart_rate_zones.json")
hr_zones=pd.json_normalize(time_in_hrzone["value"])
hr_zones["dateTime"]=time_in_hrzone["dateTime"]
hr_zones.head()

,valuesInZones.BELOW_DEFAULT_ZONE_1,valuesInZones.IN_DEFAULT_ZONE_1,valuesInZones.IN_DEFAULT_ZONE_3,valuesInZones.IN_DEFAULT_ZONE_2,dateTime
0,1254.0,164.0,0.0,3.0,2019-11-01
1,1262.0,137.0,0.0,0.0,2019-11-02
2,1218.0,141.0,0.0,0.0,2019-11-03
3,1315.0,100.0,0.0,0.0,2019-11-04
4,1300.0,94.0,12.0,7.0,2019-11-05